theme: jekyll-theme-minimal

future: true

timezone: Asia/Hong_Kong

"auto_save_on_modified": true

paginate: 5

"[markdown]": {
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true
}

"editor.codeActionsOnSave": {
    "source.fixAll.markdownlint": true
}

gem:

 'jekyll-relative-links'

plugins:
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: false